-- Migration 001: Add extended profile fields to users table

ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(500) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_url VARCHAR(500) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio_url VARCHAR(500) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(255) NULL;
